services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projetos-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: banco_iot

  mysql:
    image: mysql:5.7
    container_name: mysql-57
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco_iot
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mysql_data:
