services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projetos-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
